language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

# disable the default submodule logic
git:
  submodules: false

before_install:
# PPA for libuv-dev
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-add-repository -y ppa:linuxjedi/ppa;
      sudo apt-get -qq update;
      sudo apt-get -qq install -y libuv-dev libjson-glib-dev libgtk-3-dev ;
      sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install gtk+3 json-glib libuv;
      sed 's/git@github.com:/https:\/\/github.com\//g' .gitmodules > .temp && mv .temp .gitmodules;
    fi
  - git submodule update --init --recursive

cache:
  directories:
  - $HOME/cmake-3.4.3-Linux-x86_64
  - $HOME/cmake-3.4.3-Darwin-x86_64

install:
# Install CMake 3.4.3
  - if [[ "$TRAVIS_OS_NAME" == "linux" && (! -f "$HOME/cmake-3.4.3-Linux-x86_64/bin/cmake") ]]; then
      wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz;
      tar -xzf cmake-3.4.3-Linux-x86_64.tar.gz;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && (! -f "$HOME/cmake-3.4.3-Darwin-x86_64/bin/cmake") ]]; then
      wget --no-check-certificate http://cmake.org/files/v3.4/cmake-3.4.3-Darwin-x86_64.tar.gz;
      tar -xzf cmake-3.4.3-Darwin-x86_64.tar.gz;
    fi

script:
  - mkdir build
  - cd build
# Build project (linux)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ../cmake-3.4.3-Linux-x86_64/bin/cmake ..;
    fi
# Build project (osx)
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then
      ../cmake-3.4.3-Darwin-x86_64/CMake.app/Contents/bin/cmake .. ;
    fi
  - make client
